version: '3.8'
services:
  web:
    container_name: 'web'
    build:
      context: .
    tty: true
    working_dir: '/usr/src/app'
    volumes:
      - .:/usr/src/app:cached
    entrypoint: /bin/bash
    ports: 
      - "3000:3000"